// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wailsapp

import (
	"kineticgo/internal/repository"
	"kineticgo/internal/service"
)

// Injectors from wire.go:

func InitializeApp() *App {
	string2 := _wireStringValue
	db := repository.DbInit(string2)
	taskRepository := repository.NewTaskRepository(db)
	taskManageService := service.NewTaskManageService(taskRepository)
	app := NewApp(taskManageService)
	return app
}

var (
	_wireStringValue = "kineticgo.db"
)
