// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {json} from '../models';

export function CreateTaskSchedule(arg1:model.TaskSchedule):Promise<void>;

export function DeleteTaskSchedule(arg1:number):Promise<void>;

export function GetRunningTaskIds():Promise<Array<number>>;

export function GetTaskConfigById(arg1:number):Promise<json.RawMessage>;

export function GetTaskList():Promise<Array<model.Task>>;

export function GetTaskScheduleById(arg1:number):Promise<model.TaskSchedule>;

export function GetTaskScheduleList():Promise<Array<model.TaskSchedule>>;

export function RunTask(arg1:number):Promise<void>;

export function StopTask(arg1:number):Promise<void>;

export function UpdateTaskSchedule(arg1:model.TaskSchedule):Promise<void>;
