// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['wailsapp']['App']['ApplyUpdate'](arg1);
}

export function CheckUpdate() {
  return window['go']['wailsapp']['App']['CheckUpdate']();
}

export function CreateTaskSchedule(arg1) {
  return window['go']['wailsapp']['App']['CreateTaskSchedule'](arg1);
}

export function DeleteTaskSchedule(arg1) {
  return window['go']['wailsapp']['App']['DeleteTaskSchedule'](arg1);
}

export function DisableSystemTask(arg1) {
  return window['go']['wailsapp']['App']['DisableSystemTask'](arg1);
}

export function EnableSystemTask(arg1) {
  return window['go']['wailsapp']['App']['EnableSystemTask'](arg1);
}

export function GetPortMessage() {
  return window['go']['wailsapp']['App']['GetPortMessage']();
}

export function GetRunningTaskIds() {
  return window['go']['wailsapp']['App']['GetRunningTaskIds']();
}

export function GetSystemTaskScheduleList() {
  return window['go']['wailsapp']['App']['GetSystemTaskScheduleList']();
}

export function GetTaskConfigById(arg1) {
  return window['go']['wailsapp']['App']['GetTaskConfigById'](arg1);
}

export function GetTaskExecutions(arg1) {
  return window['go']['wailsapp']['App']['GetTaskExecutions'](arg1);
}

export function GetTaskList() {
  return window['go']['wailsapp']['App']['GetTaskList']();
}

export function GetTaskLogsByExecution(arg1) {
  return window['go']['wailsapp']['App']['GetTaskLogsByExecution'](arg1);
}

export function GetTaskScheduleById(arg1) {
  return window['go']['wailsapp']['App']['GetTaskScheduleById'](arg1);
}

export function GetTaskScheduleList() {
  return window['go']['wailsapp']['App']['GetTaskScheduleList']();
}

export function GetVersion() {
  return window['go']['wailsapp']['App']['GetVersion']();
}

export function RunPortKiller(arg1) {
  return window['go']['wailsapp']['App']['RunPortKiller'](arg1);
}

export function RunTask(arg1) {
  return window['go']['wailsapp']['App']['RunTask'](arg1);
}

export function StopTask(arg1) {
  return window['go']['wailsapp']['App']['StopTask'](arg1);
}

export function UpdateTaskSchedule(arg1) {
  return window['go']['wailsapp']['App']['UpdateTaskSchedule'](arg1);
}
